# EDA

In [1]:
#import pandas library
import pandas as pd

In [2]:
# python package installer
!pip install pandas

Requirement already satisfied: pandas in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# importing dataset
df= pd.read_csv("customer_shopping_behavior.csv")

In [4]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,913,24,Male,Hoodie,Clothing,56.0,Arkansas,M,Green,Winter,3.4,Yes,Next Day Air,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,Backpack,Accessories,53.0,Iowa,M,Gold,Spring,3.4,No,Standard,No,31.0,Debit Card,Weekly
5047,3572,70,Female,Skirt,Clothing,27.0,North Dakota,M,White,Summer,3.2,No,Standard,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,Sneakers,Footwear,52.0,Maryland,L,Gold,Summer,4.6,No,Standard,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,Blouse,Clothing,71.0,Maine,M,Cyan,Summer,3.3,No,Free Shipping,No,5.0,Bank Transfer,Every 3 Months

In [5]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

# Data Cleaning

In [6]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [7]:
df["Item Purchased"]

0          T-shirt
1       Sunglasses
2            Shirt
3           Gloves
4          Jewelry
           ...
5045        Hoodie
5046      Backpack
5047         Skirt
5048      Sneakers
5049        Blouse
Name: Item Purchased, Length: 5050, dtype: str

In [8]:
df["Item Purchased"].unique()

<StringArray>
[   'T-shirt', 'Sunglasses',      'Shirt',     'Gloves',    'Jewelry',
     'Shorts',        'Hat',    'Handbag',      'Shoes',       'Coat',
     'Laptop',     'Hoodie',      'Phone',     'Jacket',      'Pants',
   'Backpack',      'Socks',      'Jeans',        'Bag',       'Belt',
      'Watch', 'Headphones',     'Blouse',    'Sandals',      'Skirt',
    'Sweater',      'Scarf',   'Sneakers',      'Boots',      'Dress']
Length: 30, dtype: str

In [9]:
df["Category"].unique()

<StringArray>
['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear']
Length: 5, dtype: str

In [10]:
df.groupby("Category")["Item Purchased"].unique()

Category
Accessories    [Sunglasses, Gloves, Jewelry, Hat, Handbag, Ph...
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone,...
Electronics    [Laptop, Phone, Watch, Bag, Shoes, Shirt, Head...
Footwear                       [Shoes, Sandals, Sneakers, Boots]
Outerwear                                         [Coat, Jacket]
Name: Item Purchased, dtype: object

In [11]:
pd.set_option("display.max_colwidth",None)
pd.set_option("display.max_column",None)
pd.set_option("display.max_row",None)

In [12]:
df.groupby("Category")["Item Purchased"].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [16]:
correct_mapping = {

#Clothing

"T-shirt": "Clothing", "Shirt": "Clothing", "Shorts": "Clothing", "Hoodie": "Clothing", 
"Pants": "Clothing", "Socks": "Clothing", "Jeans": "Clothing", "Blouse": "Clothing", 
"Skirt": "Clothing", "Sweater": "Clothing", "Dress": "Clothing",
#Accessories
"Sunglasses": "Accessories", "Gloves": "Accessories",
"Jewelry": "Accessories", "Hat": "Accessories", 
"Handbag": "Accessories", "Backpack": "Accessories", 
"Belt": "Accessories", "Scarf": "Accessories", 
 "Bag": "Accessories",
#Electronics
"Laptop": "Electronics", "Phone": "Electronics",
"Headphones": "Electronics", "Watch": "Electronics",
#Footwear
"Shoes": "Footwear", "Sandals": "Footwear",
"Sneakers": "Footwear", "Boots": "Footwear",
#Outerwear
"Coat": "Outerwear", "Jacket": "Outerwear"
    }

In [17]:
correct_mapping

{'T-shirt': 'Clothing',
 'Shirt': 'Clothing',
 'Shorts': 'Clothing',
 'Hoodie': 'Clothing',
 'Pants': 'Clothing',
 'Socks': 'Clothing',
 'Jeans': 'Clothing',
 'Blouse': 'Clothing',
 'Skirt': 'Clothing',
 'Sweater': 'Clothing',
 'Dress': 'Clothing',
 'Sunglasses': 'Accessories',
 'Gloves': 'Accessories',
 'Jewelry': 'Accessories',
 'Hat': 'Accessories',
 'Handbag': 'Accessories',
 'Backpack': 'Accessories',
 'Belt': 'Accessories',
 'Scarf': 'Accessories',
 'Bag': 'Accessories',
 'Laptop': 'Electronics',
 'Phone': 'Electronics',
 'Headphones': 'Electronics',
 'Watch': 'Electronics',
 'Shoes': 'Footwear',
 'Sandals': 'Footwear',
 'Sneakers': 'Footwear',
 'Boots': 'Footwear',
 'Coat': 'Outerwear',
 'Jacket': 'Outerwear'}

In [18]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [19]:
df["Category"]=df["Item Purchased"].map(correct_mapping)

In [20]:
df.groupby("Category")["Item Purchased"].unique()

Category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

In [21]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

# Treating the Null Values

# Size

In [22]:
df["Size"].unique()

<StringArray>
['XL', 'M', 'L', 'S', nan]
Length: 5, dtype: str

In [23]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [24]:
df.groupby("Category") ["Size"].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [27]:
#Treating Null Values and replacing all the values in Electronics Category
df.loc[df["Category"]=="Electronics","Size"]="Not Applicable"

In [28]:
df.groupby("Category") ["Size"].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [29]:
#Treating Null Values and replacing all the values in Accessories Category
df.loc[df["Category"]=="Accessories","Size"]="Free Sazie"

In [30]:
df.groupby("Category") ["Size"].unique()

Category
Accessories          [Free Sazie]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [31]:
#Treating Null Values and replacing all the values in Footwear Category
df.loc[df["Category"]=="Footwear","Size"]="Not Available"

In [32]:
df.groupby("Category") ["Size"].unique()

Category
Accessories          [Free Sazie]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear          [Not Available]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [38]:
df.loc[(df["Category"]=="Clothing")&(df["Size"].isnull()),"Size"]=df[df["Category"]=="Clothing"]["Size"].mode()[0]

In [39]:
df.groupby("Category") ["Size"].unique()

Category
Accessories        [Free Sazie]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear        [Not Available]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

# Review Rating

In [ ]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Sazie,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Sazie,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Sazie,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [7]:
# mean of review ratings
df['Review Rating'].mean()

np.float64(3.668195100022477)

In [8]:
# median of review ratings
df['Review Rating'].median()

np.float64(3.7)

In [9]:
# mode of review ratings
df['Review Rating'].mode()

0    4.0
Name: Review Rating, dtype: float64

In [10]:
df.groupby("Item Purchased")['Review Rating'].mean()

Item Purchased
Backpack      3.758333
Bag           3.168539
Belt          3.762963
Blouse        3.677647
Boots         3.813194
Coat          3.721875
Dress         3.750000
Gloves        3.862774
Handbag       3.771975
Hat           3.796753
Headphones    3.075949
Hoodie        3.716779
Jacket        3.761446
Jeans         3.651969
Jewelry       3.761850
Laptop        3.191176
Pants         3.720833
Phone         2.939024
Sandals       3.837037
Scarf         3.702564
Shirt         3.427273
Shoes         3.546154
Shorts        3.722981
Skirt         3.779747
Sneakers      3.757931
Socks         3.755063
Sunglasses    3.745679
Sweater       3.768712
T-shirt       3.790541
Watch         3.100000
Name: Review Rating, dtype: float64

In [11]:
#Filling null values of Review Ratings with the mean of each Item Purchased
df['Review Rating']=df['Review Rating'].fillna(df.groupby('Item Purchased')['Review Rating'] .transform ('mean'))

In [12]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [13]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.200000,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.900000,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.100000,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.200000,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.600000,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.0,California,S,Beige,Summer,3.400000,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.0,Wisconsin,M,Brown,Summer,3.790541,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.0,Tennessee,M,Purple,Summer,4.000000,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.0,Florida,M,Red,Spring,4.300000,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.0,Kentucky,S,Yellow,Winter,2.800000,Yes,Store Pickup,Yes,7.0,Cash,Monthly

# Previous Purchases

In [14]:
# Filling Previous Purchases with Zero(0)
df['Previous Purchases']=df['Previous Purchases'].fillna(0)

In [15]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

# Purchase Amount (USD)

In [16]:
df.groupby("Item Purchased")['Purchase Amount (USD)'].mean()

Item Purchased
Backpack       60.111111
Bag           735.773625
Belt           59.993902
Blouse         60.802326
Boots          62.616438
Coat           57.851852
Dress          62.168675
Gloves         60.550000
Handbag        57.987261
Hat            60.787097
Headphones    831.344565
Hoodie         58.059603
Jacket         56.777108
Jeans          60.456693
Jewelry        59.011494
Laptop        805.502027
Pants          59.005848
Phone         734.477349
Sandals        57.527607
Scarf          61.157233
Shirt         279.935608
Shoes         276.343790
Shorts         60.073620
Skirt          59.723270
Sneakers       59.551724
Socks          58.188679
Sunglasses     59.975610
Sweater        57.638554
T-shirt        63.093333
Watch         685.231471
Name: Purchase Amount (USD), dtype: float64

In [17]:
#Filling null values of Purchase Amount (USD) with the mean of each Item Purchased
df['Purchase Amount (USD)']=df['Purchase Amount (USD)'].fillna(df.groupby('Item Purchased')['Purchase Amount (USD)'] .transform ('mean'))

In [18]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

# Cheaking Duplicates

In [19]:
df.duplicated().sum()

np.int64(50)

In [20]:
df[df.duplicated()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.300000,No,Free Shipping,No,19.0,Cash,Monthly
1402,1621,25,Male,Hat,Accessories,47.0,Virginia,M,Charcoal,Winter,3.100000,No,2-Day Shipping,Yes,27.0,PayPal,Every 3 Months
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.500000,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1600,2135,55,Male,Sandals,Footwear,41.0,Virginia,XL,Maroon,Winter,2.900000,No,Standard,No,35.0,Credit Card,Fortnightly
1665,1846,51,Male,Sandals,Footwear,78.0,Delaware,M,Orange,Winter,2.800000,No,2-Day Shipping,No,39.0,Bank Transfer,Quarterly
1797,3639,40,Female,Backpack,Accessories,20.0,Kansas,M,Olive,Spring,4.600000,No,Express,No,50.0,PayPal,Bi-Weekly
1870,3456,49,Female,T-shirt,Clothing,89.0,Ohio,M,Orange,Fall,4.700000,No,Standard,No,13.0,Venmo,Annually
2033,1812,42,Male,Belt,Accessories,77.0,Wisconsin,L,Blue,Summer,3.600000,No,Standard,No,33.0,Bank Transfer,Annually
2113,3040,59,Female,Blouse,Clothing,48.0,Alabama,L,Blue,Spring,3.200000,No,Next Day Air,No,31.0,PayPal,Bi-Weekly
2226,1371,27,Male,Scarf,Accessories,67.0,Montana,L,Peach,Summer,3.702564,No,2-Day Shipping,Yes,41.0,Bank Transfer,Every 3 Months
2358,2977,30,Female,Coat,Outerwear,97.0,Nebraska,M,Silver,Summer,2.800000,No,Express,No,28.0,Cash,Fortnightly
2447,2678,45,Female,Shorts,Clothing,43.0,Connecticut,L,Olive,Spring,3.800000,No,Next Day Air,No,6.0,PayPal,Every 3 Months
2630,992,20,Male,Shorts,Clothing,97.0,Wisconsin,XL,White,Spring,2.700000,Yes,Standard,Yes,40.0,Bank Transfer,Bi-Weekly
2642,1566,58,Male,Sunglasses,Accessories,93.0,Idaho,L,Peach,Fall,4.200000,No,Free Shipping,Yes,48.0,PayPal,Annually
2739,2227,22,Male,Shirt,Clothing,72.0,Missouri,L,Blue,Spring,4.800000,No,Store Pickup,No,28.0,Cash,Annually
2740,3487,51,Female,Shorts,Clothing,89.0,North Carolina,L,Charcoal,Winter,4.900000,No,Standard,No,6.0,PayPal,Weekly
2800,2069,70,Male,Jewelry,Accessories,81.0,Vermont,XL,Black,Summer,3.900000,No,Store Pickup,No,44.0,Venmo,Monthly
2905,2158,41,Male,Handbag,Accessories,68.0,Mississippi,L,Turquoise,Winter,4.000000,No,Next Day Air,No,41.0,Venmo,Fortnightly
2922,3334,55,Female,Jeans,Clothing,35.0,Minnesota,M,Violet,Spring,4.200000,No,Express,No,3.0,PayPal,Monthly
3036,258,20,Male,Handbag,Accessories,53.0,West Virginia,M,Red,Summer,4.500000,Yes,Express,Yes,5.0,Credit Card,Quarterly
3065,3887,37,Female,Jewelry,Accessories,92.0,Iowa,S,Brown,Summer,3.900000,No,Express,No,40.0,Debit Card,Quarterly
3185,1609,26,Male,Sandals,Footwear,58.0,Nebraska,XL,Cyan,Fall,4.600000,No,Next Day Air,Yes,12.0,Bank Transfer,Bi-Weekly
3357,3091,29,Female,Shirt,Clothing,36.0,Texas,M,Peach,Summer,4.900000,No,Store Pickup,No,15.0,Bank Transfer,Quarterly
3390,603,37,Male,Shoes,Footwear,58.0,Oregon,L,Lavender,Summer,4.200000,Yes,Next Day Air,Yes,10.0,Cash,Every 3 Months
3538,1698,36,Male,Shirt,Clothing,87.0,South Carolina,L,Lavender,Fall,3.500000,No,Next Day Air,No,48.0,Credit Card,Every 3 Months
3683,1209,20,Male,Boots,Footwear,100.0,Wisconsin,S,Red,Winter,3.813194,No,2-Day Shipping,Yes,8.0,Debit Card,Annually
3698,172,29,Male,Shorts,Clothing,35.0,Virginia,M,Blue,Summer,3.600000,Yes,Store Pickup,Yes,4.0,Credit Card,Weekly
3742,323,41,Male,Belt,Accessories,95.0,Tennessee,S,Cyan,Winter,3.000000,Yes,Standard,Yes,47.0,Credit Card,Monthly
3810,2429,65,Male,T-shirt,Clothing,38.0,Idaho,M,Violet,Spring,4.400000,No,Next Day Air,No,34.0,Debit Card,Annually
3843,615,68,Male,Jewelry,Accessories,85.0,Idaho,M,Lavender,Winter,4.000000,Yes,Standard,Yes,21.0,Credit Card,Bi-Weekly
3961,2558,70,Male,Shorts,Clothing,23.0,Oklahoma,L,Cyan,Spring,3.900000,No,Standard,No,17.0,PayPal,Fortnightly
3987,3507,18,Female,Shirt,Clothing,57.0,Illinois,L,Olive,Winter,3.700000,No,2-Day Shipping,No,12.0,Cash,Fortnightly
4050,3287,45,Female,Jacket,Outerwear,67.0,Illinois,L,Pink,Winter,5.000000,No,Express,No,4.0,Venmo,Fortnightly
4059,227,29,Male,Shoes,Footwear,74.0,Texas,L,Violet,Spring,3.300000,Yes,Free Shipping,Yes,5.0,PayPal,Monthly
4131,2642,25,Male,Sunglasses,Accessories,60.0,Vermont,XL,Olive,Winter,2.700000,No,Next Day Air,No,20.0,Bank Transfer,Every 3 Months
4183,1523,38,Male,Shorts,Clothing,72.0,Tennessee,L,Yellow,Spring,4.800000,No,Free Shipping,Yes,5.0,Debit Card,Monthly
4330,3716,63,Female,Sunglasses,Accessories,34.0,Nebraska,S,Orange,Fall,3.400000,No,Free Shipping,No,2.0,Bank Transfer,Monthly
4390,3846,58,Female,Sweater,Clothing,52.0,California,M,Green,Winter,4.900000,No,Standard,No,46.0,Venmo,Annually
4445,3644,53,Female,Scarf,Accessories,96.0,Tennessee,XL,Magenta,Fall,3.200000,No,Standard,No,47.0,Debit Card,Annually
4468,473,20,Male,Jeans,Clothing,39.0,Georgia,L,Gray,Winter,3.900000,Yes,Free Shipping,Yes,3.0,Bank Transfer,Quarterly
4513,1317,28,Male,Belt,Accessories,32.0,Arkansas,S,Lavender,Spring,4.600000,No,Standard,Yes,14.0,Debit Card,Bi-Weekly
4558,3339,29,Female,Skirt,Clothing,94.0,Minnesota,L,White,Winter,2.900000,No,2-Day Shipping,No,46.0,Credit Card,Monthly
4595,3577,29,Female,Boots,Footwear,24.0,Maine,L,Yellow,Spring,3.000000,No,Express,No,12.0,Venmo,Bi-Weekly
4664,2689,53,Female,Handbag,Accessories,63.0,West Virginia,XL,Turquoise,Spring,2.900000,No,2-Day Shipping,No,18.0,Credit Card,Every 3 Months
4717,2800,23,Female,T-shirt,Clothing,89.0,Maine,L,Pink,Spring,3.900000,No,Free Shipping,No,9.0,Bank Transfer,Every 3 Months
4735,2182,22,Male,Handbag,Accessories,63.0,Hawaii,M,Black,Fall,3.200000,No,Free Shipping,No,32.0,Bank Transfer,Bi-Weekly
4841,2622,48,Male,Shoes,Footwear,46.0,Maine,M,Beige,Winter,3.000000,No,Express,No,21.0,Bank Transfer,Annually
4887,3875,70,Female,Sweater,Clothing,54.0,Nevada,XL,Beige,Summer,3.900000,No,2-Day Shipping,No,33.0,Credit Card,Bi-Weekly
4901,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.500000,No,Standard,Yes,25.0,Debit Card,Monthly
5037,3439,26,Female,Shirt,Clothing,71.0,Kentucky,M,Violet,Fall,3.000000,No,Store Pickup,No,33.0,Credit Card,Monthly

In [21]:
df[df['Customer ID']==974]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
483,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.5,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.5,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly

In [22]:
len(df)

5050

In [23]:
# Deleting duplicate records
df=df.drop_duplicates(subset=['Customer ID'],keep='first')

In [24]:
len(df)

5000

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.count()

Customer ID               5000
Age                       5000
Gender                    5000
Item Purchased            5000
Category                  5000
Purchase Amount (USD)     5000
Location                  5000
Size                      4630
Color                     5000
Season                    5000
Review Rating             5000
Subscription Status       5000
Shipping Type             5000
Discount Applied          5000
Previous Purchases        5000
Payment Method            5000
Frequency of Purchases    5000
dtype: int64

In [27]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [28]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='str')

# Renaming the Headers

In [29]:
df.columns=df.columns.str.replace(" ","_")
df.columns=df.columns.str.lower()

In [30]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='str')

In [31]:
#replacing purchase_amount_(usd) to purchase_amount
df=df.rename(columns={"purchase_amount_(usd)":"purchase_amount"})

In [32]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='str')

In [33]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

# Connection to SQL Server

In [35]:
!pip install pyodbc sqlalchemy

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl (72 kB)
Downloading sqlalchemy-2.0.49-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   --------- ------------------------------ 0.5/2.1 MB 172.2 kB/s eta 0:00:10
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.8/2.1 MB 127.5 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------- -------------------- 1.0/2.1 MB 100.2 kB/s eta 0:00:11
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ------------------------ --------------- 1.3/2.1 MB 93.6 kB/s eta 0:00:09
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ----------------------------- ---------- 1.6/2.1 MB 86.3 kB/s eta 0:00:07
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 84.1 kB/s eta 0:00:04
   ---------------------------------------  2.1/2.1 MB 71.5 kB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 71.5 kB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 71.5 kB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 71.9 kB/s  0:00:27
Downloading greenlet-3.5.0-cp314-cp314-win_amd64.whl (239 kB)
Installing collected packages: pyodbc, greenlet, sqlalchemy

   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.0 pyodbc-5.3.0 sqlalchemy-2.0.49

In [1]:
import pandas as pd
df = pd.read_csv("customer_shopping_behavior.csv")
df                     # view full data
df.isnull().sum()      # check missing values

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [2]:
!pip install mysql-connector-python sqlalchemy pymysql

Requirement already satisfied: mysql-connector-python in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (9.7.0)
Requirement already satisfied: sqlalchemy in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.49)
Collecting pymysql
  Downloading pymysql-1.1.3-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.1.3-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.3

In [3]:
!pip install mysql-connector-python sqlalchemy pymysql

Requirement already satisfied: mysql-connector-python in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (9.7.0)
Requirement already satisfied: sqlalchemy in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.49)
Requirement already satisfied: pymysql in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.1.3)
Requirement already satisfied: greenlet>=1 in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)

In [4]:
from sqlalchemy import create_engine

# Fill in YOUR details here
host = "localhost"
port = 3306
user = "root"
password = "keval@2004"   # your MySQL password
database = "shopping_db"           # database you created

# Create connection
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

print("Connection successful!")

Connection successful!